### ISSUE TITLE
Restore old version

### ISSUE THREAD

**Issue by floli** [pidu/git-timemachine#28]
Restoring an old version would be really useful. Use p/n to walk to a revision and r to restore. Ask if existing file should be overwritten.

**Comment by pidu** [comment]
Suggestions are great, pull requests even better :-). Give it a try.

**Comment by pidu** [comment]
Possible complication, we now follow file renames, restoring a previous version in which the file had a different name might than cause some confusion.

**Comment by pidu** [comment]
Restoring a visited version is trivial, just need to call `write-file` manually. I think this is preferable as there is no need to consider local unsaved changes or file name changes.

**Comment by floli** [comment]
Restoring a single file using ```write-file``` surely is trivial, but doing this this on a larger set of files is not.

**Comment by pidu** [comment]
I would assume there are better ways to handle a multi file situation given that git-timemachine only works on one file at at time. Or am I missing anything?
