### ISSUE TITLE
could add subversion support?

### ISSUE THREAD

**Issue by redguardtoo** [pidu/git-timemachine#31]
like git-messenger, git-gutter

**Comment by pidu** [comment]
I would not expect something called git-<anything> to be subversion compatible neither am I a subversion user. If there is a subversion user using git-timemachine wanting to contribute a clean way to support subversion I would certainly consider merging such a pull request but that's about it. Sorry!

**Comment by pidu** [comment]
On second thought I would rather not have subversion support.
