### ISSUE TITLE
Comparison with vc-annotate  

### ISSUE THREAD

**Issue by nemethf** [pidu/git-timemachine#32]
I think it might count as a documentation bug that there isn't a short paragraph at the end of the README comparing git-timemachine with the built-in vc-annotate command.  It doesn't straightforward to see in which way git-timemachine is superior to vc-annotate.

Thanks!

**Comment by pidu** [comment]
I am making no such claim that git-timemachine is superior to vc-annotate or any other way to view versions of  a file. I am myself using vc-annotate some times and git-timemachine some other times. If anything they complement each other. 

However I think it is pretty obvious how they are different and anyone having tried both would probably agree with me. There is an animated gif showing just how not-like vc-annotate the experience is. If it's better or worse depends on what you are trying to accomplish.
