### ISSUE TITLE
show commit log instead of the hash

### ISSUE THREAD

**Issue by fommil** [pidu/git-timemachine#37]
Wow! This extension is amazing :smile:

I could only find a boolean to enable/disable the modeline info, can you please add the ability to show the log message instead of the commit id? I'm better with English instead of hexadecimal :smile:

**Comment by pidu** [comment]
Turns out I'm better with english as well so I made subject the default:

![customize group git timemachine 2015-06-24 13-09-20](https://cloud.githubusercontent.com/assets/4929249/8328740/9cffbf52-1a73-11e5-9c06-0ffb511ecdf1.png)

**Comment by fommil** [comment]
:smile:
