### ISSUE TITLE
compatible with git-gutter?

### ISSUE THREAD

**Issue by fommil** [pidu/git-timemachine#38]
Would it be possible to be able to use `git-gutter` (or similar functionality) on this? I't would be awesome to see which lines were added/changed (and where deletions were) for any time slice.

**Comment by pidu** [comment]
I think you're looking for magit-blame-mode or vc-annotate.

**Comment by fommil** [comment]
it's probably similar to `vc-annotate`, although I have never used it. Should that work? `magit-blame-mode` is a different thing, but it would be nice if it worked also.

**Comment by qinshulei** [comment]
@pidu ,magit-blame-mode or vc-annotate is different things. 

git-gutter show the changes in a more friendly way.

It would be awesome that git-timemachine get compatible with git-gutter.

[emacs-git-gutter](https://github.com/syohex/emacs-git-gutter)

![git-gutter1](https://cloud.githubusercontent.com/assets/2012618/14910434/bfaced0e-0e1f-11e6-8c33-d48dd20898d6.png)

**Comment by danrharms** [comment]
How would you select the 2 endpoint revisions to be diffed?

**Comment by qinshulei** [comment]
I think it's git-timemachine-revision and git-timemachine--next-revision .
diff git-timemachine--next-revision git-timemachine-revision
