### ISSUE TITLE
Make it work with vcsh via tramp?

### ISSUE THREAD

**Issue by QiangF** [pidu/git-timemachine#39]
Hi everyone,
Vcsh is a extremely useful software for managing multiple git repositories in the home directory. 
Is it possible to get git-timemachine recognise the repository in a file opened through tramp?

The hack to make vcsh work with magit to access VCSH repo is through TRAMP. Example, open the file /vcsh:zsh:. and then do M-x magit-status.

(add-to-list 'tramp-methods '("vcsh" (tramp-login-program "vcsh")
 (tramp-login-args (("enter")  ("%h"))) (tramp-remote-shell "/bin/sh") 
(tramp-remote-shell-args ("-c"))))

https://labo.olivierdelort.net/bricewge/dotfiles-emacs/blob/9c32a1232708137f7e247c8ceef79826ff9ff933/.emacs.d/bricewge.org

There is another attempt to integrate vcsh and magit:
https://github.com/vanicat/magit/blob/t/vcsh/magit-vcsh.el

**Comment by ikhthiandor** [comment]
:+1: This would be nice.

**Comment by pidu** [comment]
I had a look at vcsh and see the appeal. 

It remains a bit unclear to me how to reliably determine if a file is handled by vcsh. Given the suggested approach of using vcsh as a tramp method I suppose it could be deduced by looking at `buffer-file-name`.

The main obstacles seem to be the use of `vc-git-registered` and `vc-git-root` and the process-file calls in `git-timemachine--revisions` and `git-timemachine-show-revision` that would have to be gifted some vcsh capabilities when vcsh via tramp was detected.

There doesn't seem to be an insurmountable problem but as I don't use vcsh myself and this is a non trivial feature, implementing this will have to be someone else's job :-)

At the face of it it looks like implementing this would need to include doing away with some core assumptions.

**Comment by tarsius** [comment]
I recommend that you don't use `vcsh`, see https://github.com/magit/magit/issues/2939.
