### ISSUE TITLE
Preserve scroll positions

### ISSUE THREAD

**Issue by Wilfred** [pidu/git-timemachine#42]
I've noticed that git-timemachine always centres the current line. This is annoying if the previous scroll position was different.

To reproduce:
1. `C-l` `C-l` to ensure the current line is at the top of the frame (i.e. the top visible line).
2. `M-x git-timemachine` `n`
3. Observe that the current line is now in the middle of the frame.

This is different from #29 as this occurs even when the two commits have only trivial difference and have the same number of lines.

**Comment by pidu** [comment]
I looked into this without coming up with a good solution. Do you have a suggestion?

**Comment by Wilfred** [comment]
Hm, I think it's tricky. You want to avoid emptying the buffer and restoring it. Ideally, you'd only change the lines in the buffer that have changed -- this is much more reliable than trying to restore the point position, region, scroll position afterwards.

For example, the gofmt Emacs integration applies a diff to the buffer, leaving the rest unchanged: https://github.com/dominikh/go-mode.el/blob/5d53a13bd193653728e74102c81aa931b780c9a9/go-mode.el#L934

**Comment by pidu** [comment]
In that case it feels like solving this one would probably go hand-in-hand with solving #29 as one would have to deal with diffs and hunks in any case.
