### ISSUE TITLE
Missing diff indication between revisions

### ISSUE THREAD

**Issue by vikingil** [pidu/git-timemachine#44]
Hi,
Great package.
It would be nice if you will add some kind of visual indication for the diff between revisions (with the possibility to turn it on/off). See for example emacs-git-gutter or diff-hl.
Also launching ediff between nth revision to another nth revision will be helpful.

Thanks,
Vikingil

**Comment by pidu** [comment]
It would have to be toggled in that case (as you mentioned). I think there are better packages and ways to view the diffs between revisions, git-timemachine was just a quick hack to make viewing non-diffed versions easy. I mainly use magit for my diff viewing needs.

If someone finds it worthwhile to implement I would of course consider adding it in but it's nothing I'm personally missing.
