### ISSUE TITLE
Show a warning on trying to go beyond the recent commit

### ISSUE THREAD

**Issue by Wilfred** [pidu/git-timemachine#46]
It's easy to do `M-x git-timemachine RET n` and wonder why nothing's happened. It would be helpful if git-timemachine could do something like `(user-error "at most recent commit")`.

**Comment by pidu** [comment]
Solved it slightly differently but now you're not getting the empty minibuffer when next proceeds beyond the current version.

**Comment by Wilfred** [comment]
Thanks! :)
