### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by chenglou** [pidu/git-timemachine#49]
(On macbook air 2014 baseline model, 4g ram 1.3 GHz Intel Core i5)

When I have 3 atom windows open, and I close and reopen atom, git-timemachine seems to do some work that freezes the whole computer for a good 10 minutes (literally). I'm not sure what work it's doing during startup.

Really love this plugin otherwise, but as it is I can only have a single atom window open to avoid the startup freeze.

**Comment by pidu** [comment]
Sorry, but you've got the wrong project. This is an emacs extension, nothing to do with atom.

**Comment by chenglou** [comment]
Oh wow damn it. Sorry about that.
