### ISSUE TITLE
Please add a mode hook

### ISSUE THREAD

**Issue by PhilipDaniels** [pidu/git-timemachine#52]
I would like to customize the display a little, it would be nice to have a mode hook for git-timemachine-mode.

**Comment by pidu** [comment]
I'm not sure I understand, is git-timemachine-mode-hook not working for you?

**Comment by PhilipDaniels** [comment]
Sorry, I think it is my mistake - not enough Emacs understanding. I was looking through your package source code to find out the name of the hook, but it's not actually defined in there, it just appears "magically", google says from `define-minor-mode`.
