### ISSUE TITLE
Make magit-blame compatible

### ISSUE THREAD

**Issue by lepieru** [pidu/git-timemachine#57]
It will be nice to enable the magit-blame compatibility.

Like this:
- `M-x git-timemachine`
- `p p p` (i.e. move back into history)
- `M-x magit-blame`

Today, it show blames in the buffer with a `git blame` on the working copy, not on the time machine current commit.

**Comment by pidu** [comment]
Sounds easy enough to implement. We should probably bind that to a key. It's basically just to eval:

(magit-blame (car git-timemachine-revision) (buffer-file-name))

**Comment by pidu** [comment]
Bound to `b`.
