### ISSUE TITLE
Empty buffer for files with non-ascii characters in their name

### ISSUE THREAD

**Issue by thblt** [pidu/git-timemachine#60]
Time machine shows an empty buffer when the file name contains non-ASCII character.  The mode-line still shows commit IDs.  Another file from the same repository with a name composed only of standard ASCII characters doesn't exhibit the problem.

Thanks

**Comment by pidu** [comment]
Interesting. I checked this out (on OSX) and my file with non-ascii characters in the filename didn't even pass the _vc-git-registered_ test. Git on the command line also behaves badly for me. What platform are you on?

**Comment by thblt** [comment]
I'm on Debian Stretch, git and Emacs are standard packaged versions. (sorry I should have specified that in the first message)

**Comment by pidu** [comment]
@thblt Well I can confirm that this problem goes away if you

    git config [--global] core.quotepath off

Supposedly git added proper unicode support in later versions but opted to continue display non-ascii filenames in octal notation by default.

**Comment by thblt** [comment]
Thanks!
