### ISSUE TITLE
Git diff or beacon with jump in revision :)

### ISSUE THREAD

**Issue by thapakazi** [pidu/git-timemachine#62]
Not sure how much of time is available, wanted to do a feature request like:
It would be nice to have:
  - color diff or a kind of blink like [beacon](https://github.com/Malabarba/beacon) while jumping in between history.

could be asking too much, but :smiley: I can dare
Thanks for the timeline jump. Its awesome.

**Comment by pidu** [comment]
I think I get what you are requesting but perhaps what you need could be accomplished by magit-blame, it's bound to `b` in git-timemachine-mode and will run magit-blame on the currently visited revision. The problem with color diffs and their like are that they in addition to being useful can be quite distracting.

**Comment by thapakazi** [comment]
hmm, ok... I will live with blame :neckbeard:
thanks
