### ISSUE TITLE
Error when log.showSignature = true

### ISSUE THREAD

**Issue by wendelscardua** [pidu/git-timemachine#64]
I have this in my `~/.gitconfig`:

```
[log]
  showSignature = true
```

... and it breaks git-timemachine. The resulting buffer says:

```
fatal: Path 'gpg:     [REDACTED]' does not exist (neither on disk nor in the index).'
```

I think `magit` deals with this using some argument to `git log` which temporarily ignores this flag. It had the same kind of issue some time ago, apparently signature checking output is appended to whatever format is used on `git log`.

**Comment by pidu** [comment]
I had a look how magit handles this and blindly added `-c log.showSignature=false` to the git commands. I'm pretty confident that should solve the issue if not let me know.
