### ISSUE TITLE
Toggle Split Diff 

### ISSUE THREAD

**Issue by wuno** [pidu/git-timemachine#66]
When using the package split diff in Atom, the split diff can be toggled by pressing, 

`cntrl alt t`

I know git-timemachine is using it under the hood and I was wondering if the toggle feature can be used some how? 

The only key map I could find mentioned by git-timemachine was the alt t to toggle the time machine console at the bottom of the editor.

**Comment by pidu** [comment]
You've got the wrong project, this for emacs not Atom.
