### ISSUE TITLE
Choose the revision by commit message

### ISSUE THREAD

**Issue by woodensquares** [pidu/git-timemachine#67]
Not sure if you'd be ok with adding a dependency on dash.el, used here for the list functions, but I have been using this to timemachine to a specific commit message with fuzzy search on the commit message

```
(defun git-timemachine-show-revision-fuzzy ()
  "Show the revision with the chosen commit message."
  (interactive)
  (let* ((revisions (git-timemachine--revisions))
         (wanted (ivy-read
                  "Commit message: " (-select-column 5 revisions))))
    (git-timemachine-show-revision (car
                                    (-filter (lambda (candidate)
                                               (equal (nth 5 candidate) wanted))
                                             revisions)))))

(with-eval-after-load 'git-timemachine
    (bind-key (kbd "t") 'git-timemachine-show-revision-fuzzy git-timemachine-mode-map))
```

would you be interested in adding this functionality? This could also obviously use git-timemachine-completing-read-fn rather than ivy-read if that was made an option in it. This would likely be a bit slow on very large trees, I assume.

**Comment by pidu** [comment]
Nice suggestion, added :-)
